import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
  newArrFive,
  newArrSix,
  newArrSeven,
  newArrEight,
  shopProductOne,
  shopProductTwo,
  shopProductThree,
  shopProductFour,
  shopProductFive,
  shopProductSix,
  shopProductSeven,
  shopProductEight,
  shopProductNine,
  shopProductTen,
  shopProductEleven,
  shopProductTwelve,
  shopProductThirteen,
  shopProductFourteen,
  shopProductFifteen,
  shopProductSixteen,
  shopProductSeventeen,
  shopProductEighteen,
  shopProductNineteen,
  shopProductTwenty,
  shopProductTwentyOne,
  shopProductTwentyTwo,
  shopProductTwentyThree,
  shopProductTwentyFour,
  shopProductTwentyFive,
  shopProductTwentySix,
  shopProductTwentySeven,
  shopProductTwentyEight,
  shopProductTwentyNine,
  shopProductThirty,
  shopProductThirtyOne,
  shopProductThirtyTwo,

} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "/contact",
  },
  {
    _id: 1005,
    title: "Journal",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: spfOne,
    productName: "Ceiling Light",
    price: "70.00",
    color: "Black and White",
    badge: true,
    des: "This simple and clean Smart LED ceiling light is also ideal for store lighting, gallery lighting, display lighting, work lighting, product validation and home lighting.",
  },
  {
    _id: "202",
    img: spfTwo,
    productName: "iPhone 13",
    price: "650.00",
    color: "Blue",
    badge: true,
    des: "iPhone 13 Pro Max. Upgrade your camera. Super Retina XDR display with ProMotion for a faster, more responsive feel. Lightning-fast A15 Bionic chip, superfast 5G, durable design and long battery life.",
  },
  {
    _id: "203",
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Sony - WH1000XM5 Wireless Noise-Canceling Over-the-Ear Headphones.",
  },
  {
    _id: "204",
    img: spfFour,
    productName: "Refrigerator",
    price: "620.00",
    color: "Gray",
    badge: true,
    des: "Samsung - French Door Counter Depth Smart Refrigerator with AutoFill Water Pitcher.",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: 1001,
    img: spfOne,
    productName: "Smart Ceiling Light",
    price: "70.00",
    color: "Black and White",
    badge: true,
    des: "This simple and clean Smart LED ceiling light is also ideal for store lighting, gallery lighting, display lighting, work lighting, product validation and home lighting.",
  },
  {
    _id: 1002,
    img: spfTwo,
    productName: "iphone 13",
    price: "650.00",
    color: "Blue",
    badge: true,
    des: "iPhone 13 Pro Max. Upgrade your camera. Super Retina XDR display with ProMotion for a faster, more responsive feel. Lightning-fast A15 Bionic chip, superfast 5G, durable design and long battery life.",
  },
  {
    _id: 1003,
    img: spfThree,
    productName: "Headphones",
    price: "280.00",
    color: "Black",
    badge: true,
    des: "Sony - WH1000XM5 Wireless Noise-Canceling Over-the-Ear Headphones.",
  },
  {
    _id: 1004,
    img: spfFour,
    productName: "Smart Refrigerator",
    price: "620.00",
    color: "Gray",
    badge: true,
    des: "Samsung - French Door Counter Depth Smart Refrigerator with AutoFill Water Pitcher.",
  },
  {
    _id: 1005,
    img: bestSellerOne,
    productName: "Wireless Speaker",
    price: "180.00",
    color: "Black",
    badge: true,
    des: "Marshall - Kilburn II Portable Bluetooth Speaker - Black and Brass.",
  },
  {
    _id: 1006,
    img: bestSellerTwo,
    productName: "Camera Security",
    price: "250.00",
    color: "Black and White",
    badge: true,
    des: "Spotlight Camera Security Bundle - 3 Wire-Free Cameras Indoor/Outdoor 2K with Color Night Vision.",
  },
  {
    _id: 1007,
    img: bestSellerThree,
    productName: "Smart Washer",
    price: "620.00",
    color: "Black and White",
    badge: true,
    des: "Washer with Smarter Wash Technology, Easier Reach & Microban Technology.",
  },
  {
    _id: 1008,
    img: bestSellerFour,
    productName: "Apple - Ipad",
    price: "240.00",
    color: "Black, White and Gray",
    badge: true,
    des: "Apple - 10.2-Inch iPad (9th Generation) with Wi-Fi - 64GB.",
  },
  {
    _id: 1009,
    img: newArrOne,
    productName: "Radio Alarm Clock",
    price: "28.00",
    color: "Black",
    badge: true,
    des: "Stylish AM/FM Clock-radio with automatic time setting, brightness control, and gradual alarm.",
  },
  {
    _id: 1010,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Smart Watch 9 Pro Real Fixed Screw 49mm 2.19 Amoled Screen with ECG Game Wireless Charge 450Mah Men Women For Sport.",
  },
  {
    _id: 1011,
    img: newArrThree,
    productName: "Bed Lamp",
    price: "14.00",
    color: "Black",
    badge: true,
    des: "Stick Lamp with USB Charging Port and Fabric Shade - Brushed Nickel base/Black shade.",
  },
  {
    _id: 1012,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "10.00",
    color: "Gray",
    badge: true,
    des: "Repeat Talking Toy Electronic Plush Toys Can Sing Record Lighten USB Early Education Funny Gift Interactive Bled.",
  },
  {
    _id: 1013,
    img: newArrFive,
    productName: "Air Conditioner",
    price: "350.00",
    color: "White",
    badge: true,
    des: "This small air conditioner is lightweight enough to carry to any room you like, and it is a snap to install, thanks to the single hose and included window adapter.",
  },

  {
    _id: 1014,
    img: newArrSix,
    productName: "Robot Vacuum",
    price: "380.00",
    color: "Black",
    badge: true,
    des: "Shark - AI Ultra Robot Vacuum with Matrix Clean, Home Mapping, HEPA Bagless Self Empty Base, WiFI Connected.",
  },
  {
    _id: 1015,
    img: newArrSeven,
    productName: "Gaming Laptop",
    price: "820.00",
    color: "Moonlight White",
    badge: false,
    des: "ROG Zephyrus G14 14” 165Hz Gaming Laptop QHD-AMD Ryzen 7 7735HS with 16GB DDR5 Memory-NVIDIA RTX 4050 6G-512GB SSD.",
  },
  {
    _id: 1016,
    img: newArrEight,
    productName: "Foldable Drone",
    price: "40.00",
    color: "Black",
    badge: true,
    des: "This drone jam-packed with features designed to give you the cleanest view possible, including obstacle avoidance, optical flow, and real time viewing.",
  },
  //==================image thua, edit tu day====================
  {
    _id: 1017,
    img: shopProductOne,
    productName: "Modern Wall Clock",
    price: "80.00",
    color: "White and Gray",
    badge: false,
    des: "The ultimate in minimalist style, this white-faced, white-framed timepiece will be a subtle and classy addition to your room.",
  },
  {
    _id: 1018,
    img: shopProductTwo,
    productName: "Home Theater System",
    price: "420.00",
    color: "Black",
    badge: true,
    des: "Enjoy a complete home theater with the YHT-5960U. This system will transform how you listen and watch at home with a powerful subwoofer and complete set of surround speakers.",
  },
  {
    _id: 1019,
    img: shopProductThree,
    productName: "Apple - HomePod",
    price: "250.00",
    color: "Black and White",
    badge: true,
    des: " Advanced computational audio pushes acoustics further. Spatial Audio provides even more immersive sound. Works seamlessly with all your Apple devices. Connect and control your smart home, privately and securely.",
  },
  {
    _id: 1020,
    img: shopProductFour,
    productName: "Gaming Desktop",
    price: "800.00",
    color: "Black",
    badge: true,
    des: "Upgrade your current gaming rig with this iBUYPOWER Desktop. It is 16GB of 3200Mhz DDR4 RAM and Intel i5-13400F processor lets you run multiple programs at once, and its NVIDIA RTX 3060 8GB graphics card renders fast-paced action smoothly without screen tearing. This iBUYPOWER desktop also has a 500GB NVMe solid state drive for a faster start up and data acesss.",
  },
  {
    _id: 1021,
    img: shopProductFive,
    productName: "Samsung - Galaxy S23",
    price: "500.00",
    color: "Black and White",
    badge: true,
    des: "Galaxy S23 FE is jam-packed with features that help you get more out of whatever you are into including a long-lasting battery, a premium processor, a smooth and strong display, a triple-lens camera and more.",
  },
  {
    _id: 1022,
    img: shopProductSix,
    productName: "Vacuum & Self Cleaning",
    price: "320.00",
    color: "Mixed",
    badge: true,
    des: "Cleaning your floors does not need to be a stressful experience. With the Tineco Floor One S5 Extreme, say goodbye to tedious mopping, sweeping, and vacuuming. With this three-in-one vacuum, cleaning your floors just got easier, better, and more powerful.",
  },
  {
    _id: 1023,
    img: shopProductSeven,
    productName: "Lenovo LED Monitor",
    price: "120.00",
    color: "Gray",
    badge: true,
    des: "Its 1920 x 1080 FHD resolution VA panel rotates up to angles as extreme as 178°. The compact screen head is twice as slim as its previous generation and sits within a compact 3-side NearEdgeless frame.",
  },
  {
    _id: 1024,
    img: shopProductEight,
    productName: "WiFi Router",
    price: "300.00",
    color: "Black",
    badge: true,
    des: "With new WiFi 6E technology, you can enjoy ultra-fast speeds, smooth streaming, and lower latency for 4K/8K streaming, AR/VR gaming, and video conferencing. Get combined speeds of up to 10.8Gbps and a powerful 1.8GHz quad-core processor that delivers fast and reliable connections for up to 60 devices across 2,500 sq.",
  },
  {
    _id: 1025,
    img: shopProductNine,
    productName: "SONY Camera",
    price: "580.00",
    color: "Black",
    badge: true,
    des: "The ZV-E10 features a large sensor with E-mount interchangeable lens options for a wide selection of lenses, flip-out vari-angle LCD, advanced audio options and features specifically designed for vlogging.",
  },
  {
    _id: 1026,
    img: shopProductTen,
    productName: "Magnetic Power Bank",
    price: "35.00",
    color: "Black",
    badge: true,
    des: "Elevate your charging experience with the seamless integration of wireless and magnetic power. Experience the speed of 7.5W max wireless charging along with the convenience of magnetic attachment, eliminating the need for cables. Utilize the power of advanced PIQ3.0 Charging Technology, compatible with both PD and QC, and enjoy a remarkable 20W input with cable.",
  },
  {
    _id: 1027,
    img: shopProductEleven,
    productName: "Air Purifier",
    price: "80.00",
    color: "White",
    badge: true,
    des: "Keep airborne contaminants out of your home with the Levoit Core 300 Air Purifier. The Pre-Filter captures large particles like pet fur and hair. The Main Filter captures allergens like pet dander and pollen. The High-Efficiency Activated Carbon Filter’s ARC Formula adsorbs odors and chemically decomposes them to prevent second-hand pollution.",
  },
  {
    _id: 1028,
    img: shopProductTwelve,
    productName: "Professional Plus Blender",
    price: "80.00",
    color: "Black, Stainless Steel",
    badge: true,
    des: "Ninja Total Crushing Blades and Pro Extractor Blades Assembly give you perfectly crushed ice for your smoothies, frozen drinks, and nutrient extractions**. The 72 oz.† Total Crushing Pitcher is great for making large batches for the whole family with 1400 peak watts of professional power.",
  },
  {
    _id: 1029,
    img: shopProductThirteen,
    productName: "Samsung Smart TV",
    price: "180.00",
    color: "Black",
    badge: true,
    des: "Get crisp, beautiful Full HD video from this 32-inch Samsung LED Smart TV. It features Samsung's HyperReal Engine for amazing detail, color and contrast, and the smart features allow you to browse the web and cast a smartphone screen or compatible apps to the TV.",
  },
  {
    _id: 1030,
    img: shopProductFourteen,
    productName: "Full-Size Microwave",
    price: "800.00",
    color: "White, Stainless Steel",
    badge: true,
    des: "Cook quicker with this Jenn-Air microwave. It has a 1200W output to provide plenty of power for defrosting meats, and its 1.6-cu.-ft. capacity lets you reheat a whole pan of leftovers at one time.",
  },
  {
    _id: 1031,
    img: shopProductFifteen,
    productName: "Push Lawn Mower",
    price: "280.00",
    color: "Red",
    badge: true,
    des: "Get leading performance and the power of gas in a cordless mower powered by PWR CORE 20 lithium technology. The digital, brushless motor combined with two PWR CORE 20 4.0Ah lithium batteries provides unbelievable power and cutting performance.",
  },
  {
    _id: 1032,
    img: shopProductSixteen,
    productName: "Drone Toy",
    price: "20.00",
    color: "Blue",
    badge: true,
    des: "Start your drone hobby with our SP350 beginner drone, perfectly suited for indoor environments. Enjoy endless fun with the included 3 batteries which give an impressive flight time of 21 mins.",
  },
  {
    _id: 1033,
    img: shopProductSeventeen,
    productName: "Electric Pressure Cooker",
    price: "140.00",
    color: "Black",
    badge: true,
    des: "RIO Wide Plus lets you make quick and easy meals up to 70% faster** while saving up to 60% on energy. We’ve captured all the features, convenience and delicious results we love about the popular Duo Plus with a modern design and more cooking area than a 12 skillet. RIO Wide Plus has a 35% larger searing surface*, letting you cook more food at once, from a 5 lb chicken to a 9” springform cake pan and more.",
  },
  {
    _id: 1034,
    img: shopProductEighteen,
    productName: "LED Desk Lamp with Wireless Charging",
    price: "25.00",
    color: "Black",
    badge: true,
    des: "Set yourself and your student up for success with the OttLite Organizer LED Desk Lamp w/Wireless Charging. With OttLite’s clear LED light you’ll enjoy dramatically reduced eyestrain for hours of focused, productive learning. Having a dedicated study area with healthy lighting and reduced distractions is a perfect formula for student success.",
  },
  {
    _id: 1035,
    img: shopProductNineteen,
    productName: "Asus LCD Monitor",
    price: "90.00",
    color: "Black",
    badge: true,
    des: "ASUS VA24EHE Eye Care Monitor features 23.8 inch IPS panel with Full HD (1920 x 1080) resolution, providing 178° wide viewing angle panel and vivid image quality. Up to 75Hz refresh rate with Adaptive-Sync/FreeSync™ technology to eliminate tracing and ensure crisp and clear video playback.",
  },
  {
    _id: 1036,
    img: shopProductTwenty,
    productName: "Coffee & Espresso Machine",
    price: "160.00",
    color: "Black",
    badge: true,
    des: "Nespresso introduces the VertuoPlus by De'Longhi, with an all-new design and colors for the ultimate brewing experience. Offering freshly brewed Coffee with crema as well as delicious, authentic Espresso, the VertuoPlus coffee machine conveniently makes 4 cup sizes at the touch of a button: 5oz, 8oz Coffee and single and double Espresso. Each machine includes a complimentary welcome set with a range of Nespresso pods Vertuo with unique aroma profiles.",
  },
  {
    _id: 1037,
    img: shopProductTwentyOne,
    productName: "Virtual Reality Headset",
    price: "250.00",
    color: "Gray",
    badge: true,
    des: "Meta Quest 2 is the all-in-one system that truly sets you free to roam in VR with no wires or cables to limit your experience. A super-fast processor and high-resolution display help to keep your experience smooth and seamless, even as high speed action unfolds around you.",
  },
  {
    _id: 1038,
    img: shopProductTwentyTwo,
    productName: "Google - Pixel 8 Pro",
    price: "750.00",
    color: "BlackObsidian",
    badge: true,
    des: "Introducing Pixel 8 Pro, the all-pro phone engineered by Google. It’s sleek, sophisticated, powerful, and secure. With Google AI, you can do more, even faster.",
  },
  {
    _id: 1039,
    img: shopProductTwentyThree,
    productName: "Microsoft - Surface Pro",
    price: "550.00",
    color: "Platinum",
    badge: true,
    des: "Classic Surface Pro 2-in-1 design meets high-speed performance, giving you premium laptop power, a powerful tablet, or portable digital canvas designed to light up the best of Windows 11.",
  },
  {
    _id: 1040,
    img: shopProductTwentyFour,
    productName: "Smart Lock",
    price: "180.00",
    color: "Black",
    badge: true,
    des: "YALE ASSURE 2 TOUCH. A lock as unique as you. Make coming home more seamless with the Yale Assure Lock 2 Touch built-in Wi-Fi. Thanks to the new biometric keypad, a simple touch of your finger is all it takes.",
  },
  {
    _id: 1041,
    img: shopProductTwentyFive,
    productName: "Smart Speaker",
    price: "30.00",
    color: "Black",
    badge: true,
    des: "Smart speaker features a sleek design and improved audio for vibrant sound anywhere in your home. With Echo Dot, you can stay on track with help from Alexa, control compatible smart home devices and start routines with your motion.",
  },
  {
    _id: 1042,
    img: shopProductTwentySix,
    productName: "Electric Space Heater",
    price: "35.00",
    color: "Black",
    badge: true,
    des: "Lasko's Simple Touch ceramic space heater is perfect for desktop or tabletop, and delivers 1500 watts of quick, fan-powered ceramic warmth. This little portable heater features key safety features, including a cool-touch exterior, self-regulating ceramic element, and automatic overheat protection.",
  },
  {
    _id: 1043,
    img: shopProductTwentySeven,
    productName: "Mesh Wi-Fi System",
    price: "180.00",
    color: "White",
    badge: true,
    des: "Create a strong whole-home network with this ASUS ZenWifi AX Mini Wi-Fi 6 system. The three dual-band mesh routers support speeds of up to 3000 Mbps for smooth high-bandwidth streaming on multiple devices.",
  },
  {
    _id: 1044,
    img: shopProductTwentyEight,
    productName: "Floorstanding Speaker",
    price: "160.00",
    color: "Black",
    badge: true,
    des: "Enjoy room-filling sound with this Sony Core Series SSCS3 floorstanding speaker, which features dual 5 woofers, a 3/4 super tweeter and a 1 tweeter to precisely reproduce instruments and vocals in robust detail.",
  },
  {
    _id: 1045,
    img: shopProductTwentyNine,
    productName: "Electric Range",
    price: "820.00",
    color: "Stainless Steel",
    badge: true,
    des: "This smart Front Control Slide-in Range includes Air Fry, Convection & is fully Wi-fi connected and voice enabled, making it easy to create delicious meals for your family fast.",
  },
  {
    _id: 1046,
    img: shopProductThirty,
    productName: "Window Conditioner",
    price: "350.00",
    color: "White",
    badge: true,
    des: "This Hisense AW1221DR3W 3 speed window air conditioner with remote control features dehumidifier and heat functions. This 11,500 BTU capacity window air conditioner with 10,700 BTU powerful heat function can be placed in rooms up to 550 sq.ft and is easy-to-install with the included kit for windows 27 – 41 inches wide. Additional features include a quiet compressor, and a new quiet operation design (provides quiet operation, 56 dB on low), programmable 24-hour on/off timer, dimmable LED digital controls, and 4-way airflow adjustment.",
  },
  {
    _id: 1047,
    img: shopProductThirtyOne,
    productName: "iPhone 15 Pro Max",
    price: "1200.00",
    color: "Titan",
    badge: true,
    des: "iPhone 15 Pro Max. Forged in titanium and featuring the groundbreaking A17 Pro chip, a customizable Action button, and the most powerful iPhone camera system ever.",
  },
  {
    _id: 1048,
    img: shopProductThirtyTwo,
    productName: "Self-Balancing Scooter",
    price: "60.00",
    color: "Black",
    badge: true,
    des: "Have a blast with the Hover-1 Blast Hoverboard. This fast, powerful, and versatile hoverboard shines bright with integrated LED lighting. Not to mention the dual 160W motors get you to wherever you want to go quickly. With a maximum ride range of 3 miles, you can zip back and forth at warp speed.",
  },
];
// =================== PaginationItems End here =================
